<?php
require_once 'redir.php';
include 'header.php';
?>
<h2>Full Analysis Workflow</h2>
<p>
    This workflow fetches protein sequences from NCBI directly and processes them through multiple analysis steps. Please note that in order to keep waiting times short and prevent issues with data retrieval, if your query returns more than 500 sequences, a warning will be displayed. If you decide to proceed anyway, waiting time may vary. The current website settings allow a maximum of 50 protein records to be imported regardless of the original number of returned sequences. The downstream analysis will be performed on the 50 imported protein records. You can download any file generated by any step of the workflow directly through the link at the bottom of each page or review all the downloadable files relevant to a full analysis from the Job History page. Please note down the job ID you will be given in the next step as it will identify uniqly your analysis and any relevant files.
</p>

<!-- Custom Query Form -->
<form action="fetch_protein_custom.php" method="post">
    <label>Protein Family:</label>
    <input type="text" name="protein_family" required><br>
    <label>Taxonomic Group:</label>
    <input type="text" name="taxonomic_group" required><br>
    <input type="submit" value="Retrieve Sequences" class="menu-button">
</form>
<p><small>This step fetches sequences from NCBI and may take a few moments.</small></p>

<?php include 'footer.php'; ?>

